Repository To-Letter/To-Letter-front, pull requests merged in 2025-01, with the labels that each got.

#103 [feat] seo meta tag root layout
  src/app/@modal/auth/layout.tsx
  src/app/@modal/letter/letterbox/layout.tsx
  src/app/@modal/letter/letterdelete/layout.tsx
  src/app/@modal/letter/newletter/layout.tsx
  src/app/@modal/mypage/layout.tsx
  src/app/layout.tsx
  src/components/ClientProviders.tsx
  src/components/molecules/MenuTab.tsx
Labels: feature

#105 [fix] modal path name bug
  src/app/layout.tsx
  src/components/ClientProviders.tsx
  src/components/atoms/Box.tsx
  src/components/canvas/models/Desk.tsx
  src/components/organisms/letter/LetterWriteContents.tsx
  src/components/organisms/letter/NicknameConfirmContents.tsx
Labels: bug

#106 [feat] seo metadata
  public/icon/apple-touch-icon.png
  public/icon/favicon-16x16.png
  public/icon/favicon-32x32.png
  public/images/openGraph/kakao_card.png
  public/images/openGraph/og_image.png
  src/app/@modal/auth/login/page.tsx
  src/app/layout.tsx
  src/app/robots.ts
  src/app/sitemap.ts
Labels: feature

#107 Server api connection
  src/app/page.tsx
  src/app/users/deleteKakao/page.tsx
  src/app/users/kakao/page.tsx
  src/components/canvas/Scene.tsx
  src/components/canvas/models/Bed.tsx
  src/components/canvas/models/Books.tsx
  src/components/canvas/models/Bookshelf.tsx
  src/components/canvas/models/Desk.tsx
  src/components/canvas/models/Photo.tsx
  src/components/canvas/models/TrashBin.tsx
  src/components/organisms/auth/AddressContents.tsx
  src/components/organisms/auth/KakaoSignupContents.tsx
  src/components/organisms/auth/LoginContents.tsx
  src/components/organisms/auth/MailVerifyContents.tsx
  src/components/organisms/auth/SignupContents.tsx
  src/components/organisms/mypage/KakaoUserDeleteContents.tsx
  src/components/organisms/mypage/KakaoUserWithdrawContents.tsx
  src/components/organisms/mypage/LetterEndContents.tsx
  src/components/organisms/mypage/LocalUserDeleteContents.tsx
  src/components/organisms/mypage/MyInfoContents.tsx
  src/components/organisms/mypage/PasswordChangeContents.tsx
  src/components/organisms/mypage/PasswordMailVerifyContents.tsx
  src/constants/authkey.ts
  src/hooks/useUser.ts
  src/lib/api/axiosInterceptor.ts
  src/lib/api/controller/account.ts
  src/lib/api/sendApi.ts
  src/store/recoil/accountAtom.ts
Labels: feature

#108 [feat, perf] users guide page
  package.json
  postcss.config.js
  postcss.config.mjs
  public/images/guide/roomBed.png
  public/images/guide/roomDesk.png
  public/images/guide/roomDeskUser.png
  public/images/guide/roomTrash.png
  public/images/guideStart.png
  public/images/guideWait.png
  src/app/guide/page.tsx
  src/app/layout.tsx
  src/app/page.tsx
  src/app/robots.ts
  src/app/sitemap.ts
  src/components/atoms/GuideLoading.tsx
  src/components/canvas/Scenery/Autumn.tsx
  src/components/canvas/Scenery/SeasonBackground.tsx
  src/components/canvas/Scenery/Snow.tsx
  src/components/canvas/Scenery/Spring.tsx
  src/components/canvas/Scenery/Summer.tsx
  src/components/canvas/Scenery/Winter.tsx
  src/components/canvas/models/Bed.tsx
  src/components/canvas/models/Books.tsx
  src/components/canvas/models/Chair.tsx
  src/components/canvas/models/Desk.tsx
  src/components/canvas/models/Drawer.tsx
  src/components/canvas/models/Lamp.tsx
  src/components/canvas/models/NewLetter.tsx
  src/components/canvas/models/TrashBin.tsx
  src/components/canvas/models/Window.tsx
  src/components/molecules/SlideCard.tsx
  src/components/organisms/guide/Slide.tsx
  src/components/template/CSRGuidePage.tsx
  src/components/template/GuidePage.tsx
  src/hooks/useGLTFLoader.ts
  src/lib/constants/guideValue.ts
  src/store/recoil/zustand/modelLoadingStore.ts
  src/style/globals.css
  tailwind.config.js
  tailwind.config.ts
Labels: feature

#114 [Fix] guide page css 깨짐 처리 #66
  src/components/atoms/GuideLoading.tsx
  src/components/molecules/SlideCard.tsx
  src/components/organisms/guide/Slide.tsx
  src/style/guide-loading.css
Labels: fix

#115 fix: url 직접 접근시 가이드 페이지로 redirect #87
  next.config.js
  src/app/page.tsx
  src/middleware.ts
Labels: fix

#118 Hotfix/verify text
  src/app/@modal/auth/layout.tsx
  src/components/atoms/ModalBox.tsx
  src/components/organisms/auth/KakaoSignupContents.tsx
  src/components/organisms/auth/MailVerifyContents.tsx
  src/components/organisms/auth/SignupContents.tsx
  src/store/recoil/accountAtom.ts
Labels: fix

#119 fix: 카카오 로그인 리다이렉트 가이드 페이지로 연결되는 에러 제거
  src/app/page.tsx
Labels: fix
